# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c38de69946088dbd5ba1e015c72637244e8f0646a354aba92a6fb0ec2c8d7649ed742a026f1d921d39f69ba39602bc29d6db5019aa851ff4db5dd56aa0c55cb1

test:
  secret_key_base: bfc548e6fed3599a51e699ebdf307f2f49fe7a922001cf9e83cbc762c1abf80b9875af0ae45e57721c17b8febf94478d6d479c71fc4aae5af3253ba5bf572383

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
